//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BentleyModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int Id { get; set; }
        public int CommitteeId { get; set; }
        public float Amount { get; set; }
        public string Year { get; set; }
        public string Description { get; set; }
    
        public virtual Committee Committee { get; set; }
    }
}
